version: '3'

services:
  tor:
    image: dperson/torproxy
    restart: unless-stopped
    ports:
      - "9050:9050"

  screenshot-api:
    build: .
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - tor
